// Initial phrases for seeding the database
export const initialPhrases = [
  // Staff Section Phrases
  { 
    id: 'staff_general_1',
    type: 'staff', 
    category: 'General Enquiries', 
    english: 'Please follow me.',
    translations: {
      'zh-CN': '请跟我来。', 
      'zh-HK': '请跟我来。', 
      'ne-NP': 'कृपया मलाई पछ्याउनुहोस्。',
      'el-GR': 'Παρακαλώ ακολουθήστε με。', 
      'ar-SA': 'الرجاء اتبعني。', 
      'mk-MK': 'Ве мо lám следете me。',
      'es-ES': 'Por favor, sígame。', 
      'it-IT': 'Per favor, mi segua。',
      'id-ID': 'Tolong ikiti saya。', 
      'en-US': 'Please follow me.',
    }
  },
  { 
    id: 'staff_general_2',
    type: 'staff', 
    category: 'General Enquiries', 
    english: 'Do you prefer to speak Mandarin or Cantonese?',
    translations: {
      'zh-CN': '您更喜欢说普通话还是粤语？',
      'zh-HK': '你鍾意講普通話定廣東話？',
      'ne-NP': 'तपाईं मन्डारिन वा क्यान्टोनिज बोल्न रुचाउनुहुन्छ?',
      'el-GR': 'Προτιμάτε να μιλάτε Μανδαarinika ή Καντονέζικα？',
      'ar-SA': 'هل تفضل التحدث بالماندرين أو الكانتونية؟',
      'mk-MK': 'Дали претpočitate να зборувате μαndaринiski or кантонски？',
      'es-ES': '¿Prefiere hablar mandarín o cantonés？', 
      'it-IT': 'Preferisce parlare mandarino or cantonese？',
      'id-ID': 'Apakah Anda more like to speak Mandarin or Kanton？',
      'en-US': 'Do you prefer to speak Mandarin or Cantonese?',
    }
  },
  { 
    id: 'staff_general_3',
    type: 'staff', 
    category: 'General Enquiries', 
    english: 'I speak Mandarin.',
    translations: {
      'zh-CN': '我会说普通话。',
      'zh-HK': '我識講普通話。',
      'ne-NP': 'म मन्डारिन बोल्छु。',
      'el-GR': 'Μιλάω Μανδαρινικά。', 
      'ar-SA': 'أنا أتحدث الماندايرين。', 
      'mk-MK': 'Зборуам μαndaринiski。',
      'es-ES': 'Hablo mandarín。', 
      'it-IT': 'Parlo mandarino。',
      'id-ID': 'Saya berbicara Mandarin。', 
      'en-US': 'I speak Mandarin.',
    }
  },
  { 
    id: 'staff_general_4',
    type: 'staff', 
    category: 'General Enquiries', 
    english: 'I speak Cantonese.',
    translations: {
      'zh-CN': '我会说粤语。',
      'zh-HK': '我識講廣東話。',
      'ne-NP': 'म क्यान्टोनिज बोल्छु。',
      'el-GR': 'Μιλάω Καντονέζικα。', 
      'ar-SA': 'أنا أتحدث الكانتونية。', 
      'mk-MK': 'Зoruam кантонски。',
      'es-ES': 'Hablo cantonés。', 
      'it-IT': 'Parlo cantonese。',
      'id-ID': 'Saya berbicara Kanton。', 
      'en-US': 'I speak Cantonese.',
    }
  },
  { 
    id: 'staff_general_5',
    type: 'staff', 
    category: 'General Enquiries', 
    english: 'Please wait one moment',
    translations: {
      'zh-CN': '请稍等片刻。', 
      'zh-HK': '请你稍等一陣。', 
      'ne-NP': 'कृपया एक क्षण पर्खनुहोस्।',
      'el-GR': 'Παρακαλώ περιμένετε μια στιγμή。', 
      'ar-SA': 'الرجاء الانت 기다리다。', 
      'mk-MK': 'Ве моlam počekajte moment。',
      'es-ES': 'Por favor, espere un momento。', 
      'it-IT': 'Per favor, aspetti un momento。',
      'id-ID': 'Mohon tunggu sebentar。', 
      'en-US': 'Please wait one moment',
    }
  },
  { 
    id: 'staff_general_6',
    type: 'staff', 
    category: 'General Enquiries', 
    english: 'I understand.',
    translations: {
      'zh-CN': '我明白了。', 
      'zh-HK': '我明白喇。', 
      'ne-NP': 'मैले बुझें。',
      'el-GR': 'Καταλαβαίνω。', 
      'ar-SA': 'أنا أفهم。', 
      'mk-MK': 'Разбирам。',
      'es-ES': 'Entiendo。', 
      'it-IT': 'Capisco。',
      'id-ID': 'Saya mengerti。', 
      'en-US': 'I understand.',
    }
  },
  { 
    id: 'staff_general_7',
    type: 'staff', 
    category: 'General Enquiries', 
    english: 'Thank you.',
    translations: {
      'zh-CN': '谢谢您。', 
      'zh-HK': '多謝你。', 
      'ne-NP': 'धन्यवाद।',
      'el-GR': 'Ευχαριστώ。', 
      'ar-SA': 'شكرا لك。', 
      'mk-MK': 'Ви благодаруваме。',
      'es-ES': 'Salamat po。', 
      'it-IT': 'Grazie。',
      'id-ID': 'Terima kindness。', 
      'en-US': 'Thank you.',
    }
  },
  { 
    id: 'staff_general_8',
    type: 'staff', 
    category: 'General Enquiries', 
    english: 'You are welcome.',
    translations: {
      'zh-CN': '不客气。', 
      'zh-HK': '唔使客氣。', 
      'ne-NP': 'तपाईंलाई स्वागत छ।',
      'el-GR': 'Παρακαλώ。', 
      'ar-SA': 'على الرحب والسعة。', 
      'mk-MK': 'Неμα na што。',
      'es-ES': 'De nada。', 
      'it-IT': 'Prego。',
      'id-ID': 'Sama-sama。', 
      'en-US': 'You are welcome.',
    }
  },
  { 
    id: 'staff_transactional_1',
    type: 'staff', 
    category: 'Transactional', 
    english: 'Please show me your library card',
    translations: {
      'zh-CN': '请出示您的借书证', 
      'zh-HK': '请出示你的图书证。', 
      'ne-NP': 'कृपया आफ्नो पुस्तकालय कार्ड देखाउनुहोस्।',
      'el-GR': 'Παρακαλώ δείξτε μου την κάρτα βιβλιοθήκης σας。', 
      'ar-SA': 'الرجاء إظهار بطاقة المكتبة الخاصة بك。', 
      'mk-MK': 'Ве мо lám pokažete mi ja vašata bibliotečna kartička。',
      'es-ES': 'Por favor, muéstreme su tarjeta de la biblioteca。', 
      'it-IT': 'Per favor, mi mostri la sua tessera della biblioteca。',
      'id-ID': 'Tolong tunjukkan kartu perpustakaan Anda。', 
      'en-US': 'Please show me your library card',
    }
  },
  { 
    id: 'staff_transactional_2',
    type: 'staff', 
    category: 'Transactional', 
    english: 'Would you like to create a library card? It is free of charge.',
    translations: {
      'zh-CN': '您想办一张借书证吗？这是免费的。', 
      'zh-HK': '你想申请张图书证吗？系免费嘅。', 
      'ne-NP': 'के तपाईं पुस्तकालय कार्ड बनाउन चाहनुहुन्छ? यो निःशुल्क छ।',
      'el-GR': 'Θα θέlaτε να βγάλετε κάρτα βιβλιοθήκης; Είναι δω ücretsiz。', 
      'ar-SA': 'هل ترغب في إنشاء بطاقة مكتبة؟إنها مجانية。', 
      'mk-MK': 'Дали сакате да napravite bibliotečna kartička? Besplatno e。',
      'es-ES': '¿Le gustaría crear una tarjeta de la biblioteca? Es gratis。', 
      'it-IT': 'Le piacerebbe creare una tessera della biblioteca? È gratuita。',
      'id-ID': 'Apakah Anda ingin membuat kartu perpustakaan? This is free of charge。', 
      'en-US': 'Would you like to create a library card? It is free of charge.',
    }
  },
  { 
    id: 'staff_transactional_3',
    type: 'staff', 
    category: 'Transactional', 
    english: 'Would you like to borrow these items?',
    translations: {
      'zh-CN': '您想借阅这些物品吗？', 
      'zh-HK': '你想借呢啲嘢嗎？', 
      'ne-NP': 'के तपाईं यी सामानहरू उधारो लिन चाहनुहुन्छ?',
      'el-GR': 'Θα θέlaτε να δανειστείτε αυτά τα αντικείμενα？', 
      'ar-SA': 'هل ترغب في استعارة هذه المواد؟', 
      'mk-MK': 'Дали сакате da gi pozajmite ovie predmeti？',
      'es-ES': '¿Le gustaría pedir prestados estos artículos？', 
      'it-IT': 'Le piacerebbe prendere in prestito these items？',
      'id-ID': 'Apakah Anda ingin meminjam barang-abag this？', 
      'en-US': 'Would you like to borrow these items?',
    }
  },
  { 
    id: 'staff_transactional_4',
    type: 'staff', 
    category: 'Transactional', 
    english: 'Would you like to return these items?',
    translations: {
      'zh-CN': '您想归还这些物品吗？', 
      'zh-HK': '你想还呢啲嘢嗎？', 
      'ne-NP': 'के तपाईं यी सामानहरू फिर्ता गर्न चाहनुहुन्छ?',
      'el-GR': 'Θα θέlaτε να επιστρέψετε αυτά τα αντικείμενα？', 
      'ar-SA': 'هل ترغب في إرجاع هذه المواد؟', 
      'mk-MK': 'Дали сакате da gi vratite ovie predmeti？',
      'es-ES': '¿Le gustaría devolver estos artículos？', 
      'it-IT': 'Le piacerebbe restituire these items？',
      'id-ID': 'Apakah Anda ingin mengembalikan barang-barang this？', 
      'en-US': 'Would you like to return these items?',
    }
  },
  // Staff General Enquiries - additional phrases
  {
    id: 'staff_general_9',
    type: 'staff',
    category: 'General Enquiries',
    english: 'Can I help you?',
    translations: {
      'zh-CN': '我可以帮您吗？',
      'zh-HK': '我可以幫你嗎？',
      'ne-NP': 'के म तपाईंलाई मद्दत गर्न सक्छु?',
      'el-GR': 'Μπορώ να σας βοηθήσω；',
      'ar-SA': 'هل يمكنني مساعدتك؟',
      'mk-MK': 'Можам ли да ви помогнам？',
      'es-ES': '¿Puedo ayudarle？',
      'it-IT': 'Posso aiutarla？',
      'id-ID': 'Bisakah saya membantu Anda？',
      'en-US': 'Can I help you?',
    }
  },
  {
    id: 'staff_general_10',
    type: 'staff',
    category: 'General Enquiries',
    english: 'Do you understand?',
    translations: {
      'zh-CN': '您明白了吗？',
      'zh-HK': '你明白嗎？',
      'ne-NP': 'के तपाईंलाई बुझ्नु भयो?',
      'el-GR': 'Καταλαβαίνετε；',
      'ar-SA': 'هل تفهم؟',
      'mk-MK': 'Дали разбирате？',
      'es-ES': '¿Entiende？',
      'it-IT': 'Capisce？',
      'id-ID': 'Apakah Anda mengerti？',
      'en-US': 'Do you understand?',
    }
  },
  {
    id: 'staff_general_11',
    type: 'staff',
    category: 'General Enquiries',
    english: 'Please speak slowly.',
    translations: {
      'zh-CN': '请讲慢一点。',
      'zh-HK': '請講慢啲。',
      'ne-NP': 'कृपया बिस्तारै बोल्नुहोस्।',
      'el-GR': 'Παρακαλώ μιλάτε αργά。',
      'ar-SA': 'الرجاء التحدث ببطء。',
      'mk-MK': 'Ве молам зборувајте бавно。',
      'es-ES': 'Por favor, hable despacio。',
      'it-IT': 'Per favore, parli lentamente。',
      'id-ID': 'Tolong berbicara perlahan。',
      'en-US': 'Please speak slowly.',
    }
  },
  {
    id: 'staff_general_12',
    type: 'staff',
    category: 'General Enquiries',
    english: 'I will get someone who can help you.',
    translations: {
      'zh-CN': '我去找人来帮您。',
      'zh-HK': '我去搵個人嚟幫你。',
      'ne-NP': 'म तपाईंलाई मद्दत गर्न सक्ने कोहीलाई ल्याउँछु।',
      'el-GR': 'Θα φέρω κάποιον που μπορεί να σας βοηθήσει。',
      'ar-SA': 'سأحضر شخصًا يمكنه مساعدتك。',
      'mk-MK': 'Ќе доведам некој кој може да ви помогне。',
      'es-ES': 'Voy a buscar a alguien que pueda ayudarle。',
      'it-IT': 'Vado a cercare qualcuno che possa aiutarla。',
      'id-ID': 'Saya akan mencari seseorang yang bisa membantu Anda。',
      'en-US': 'I will get someone who can help you.',
    }
  },
  // Staff Transactional - additional phrases
  {
    id: 'staff_transactional_9',
    type: 'staff',
    category: 'Transactional',
    english: 'Your reservation is ready for pickup.',
    translations: {
      'zh-CN': '您的预约物品已备好，请取用。',
      'zh-HK': '你的預約物品已準備好，請取用。',
      'ne-NP': 'तपाईंको आरक्षण उठाउन तयार छ।',
      'el-GR': 'Η κράτησή σας είναι έτοιμη για παραλαβή。',
      'ar-SA': 'حجزك جاهز للاستلام。',
      'mk-MK': 'Вашата резервација е готова за подигање。',
      'es-ES': 'Su reserva está lista para recoger。',
      'it-IT': 'La sua prenotazione è pronta per il ritiro。',
      'id-ID': 'Reservasi Anda siap untuk diambil。',
      'en-US': 'Your reservation is ready for pickup.',
    }
  },
  {
    id: 'staff_transactional_10',
    type: 'staff',
    category: 'Transactional',
    english: 'Would you like to pay by cash or card?',
    translations: {
      'zh-CN': '您想付现金还是刷卡？',
      'zh-HK': '你想用現金定卡付款？',
      'ne-NP': 'के तपाईं नगद वा कार्डले भुक्तानी गर्न चाहनुहुन्छ?',
      'el-GR': 'Θα θέλατε να πληρώσετε με μετρητά ή κάρτα；',
      'ar-SA': 'هل تريد الدفع نقداً أم ببطاقة؟',
      'mk-MK': 'Дали сакате да платите со готовина или картичка？',
      'es-ES': '¿Le gustaría pagar en efectivo o con tarjeta？',
      'it-IT': 'Vuole pagare in contanti o con carta？',
      'id-ID': 'Apakah Anda ingin membayar tunai atau dengan kartu？',
      'en-US': 'Would you like to pay by cash or card?',
    }
  },
  {
    id: 'staff_transactional_11',
    type: 'staff',
    category: 'Transactional',
    english: 'These items are for reference only and cannot be borrowed.',
    translations: {
      'zh-CN': '这些物品仅供参考，不能借出。',
      'zh-HK': '呢啲物品只供參考，唔可以借出。',
      'ne-NP': 'यी वस्तुहरू केवल सन्दर्भको लागि हुन् र उधारो लिन सकिँदैन।',
      'el-GR': 'Αυτά τα αντικείμενα είναι μόνο για αναφορά και δεν μπορούν να δανειστούν。',
      'ar-SA': 'هذه المواد للرجوع إليها فقط ولا يمكن استعارتها。',
      'mk-MK': 'Овие предмети се само за референца и не можат да се позајмат。',
      'es-ES': 'Estos artículos son solo de consulta y no se pueden prestar。',
      'it-IT': 'Questi articoli sono solo di consultazione e non possono essere prestati。',
      'id-ID': 'Barang-barang ini hanya untuk referensi dan tidak dapat dipinjam。',
      'en-US': 'These items are for reference only and cannot be borrowed.',
    }
  },
  // Staff Digital Services - additional phrases
  {
    id: 'staff_digital_6',
    type: 'staff',
    category: 'Digital Services',
    english: 'Would you like to use a scanner?',
    translations: {
      'zh-CN': '您想使用扫描仪吗？',
      'zh-HK': '你想用掃描器嗎？',
      'ne-NP': 'के तपाईं स्क्यानर प्रयोग गर्न चाहनुहुन्छ?',
      'el-GR': 'Θα θέλατε να χρησιμοποιήσετε τον σαρωτή；',
      'ar-SA': 'هل ترغب في استخدام الماسح الضوئي؟',
      'mk-MK': 'Дали сакате да го користите скенерот？',
      'es-ES': '¿Le gustaría usar el escáner？',
      'it-IT': 'Le piacerebbe usare lo scanner？',
      'id-ID': 'Apakah Anda ingin menggunakan pemindai？',
      'en-US': 'Would you like to use a scanner?',
    }
  },
  {
    id: 'staff_digital_7',
    type: 'staff',
    category: 'Digital Services',
    english: 'You have limited time remaining on the computer.',
    translations: {
      'zh-CN': '您在电脑上的时间即将结束。',
      'zh-HK': '你用電腦嘅時間快完喇。',
      'ne-NP': 'कम्प्युटरमा तपाईंको समय सीमित बाँकी छ।',
      'el-GR': 'Ο χρόνος σας στον υπολογιστή είναι περιορισμένος。',
      'ar-SA': 'تبقى لك وقت محدود على الحاسوب。',
      'mk-MK': 'Ви останало ограничено време на компјутерот。',
      'es-ES': 'Le queda poco tiempo en el ordenador。',
      'it-IT': 'Ha poco tempo rimanente sul computer。',
      'id-ID': 'Anda memiliki waktu terbatas yang tersisa di komputer。',
      'en-US': 'You have limited time remaining on the computer.',
    }
  },
  // Customer General Assistance - additional phrases
  {
    id: 'customer_general_9',
    type: 'customer',
    category: 'General Assistance',
    english: 'I need help finding a book.',
    translations: {
      'zh-CN': '我需要帮助找一本书。',
      'zh-HK': '我需要幫助搵一本書。',
      'ne-NP': 'मलाई किताब खोज्न मद्दत चाहिन्छ।',
      'el-GR': 'Χρειάζομαι βοήθεια να βρω ένα βιβλίο。',
      'ar-SA': 'أحتاج مساعدة في إيجاد كتاب。',
      'mk-MK': 'Ми треба помош да најдам книга。',
      'es-ES': 'Necesito ayuda para encontrar un libro。',
      'it-IT': 'Ho bisogno di aiuto per trovare un libro。',
      'id-ID': 'Saya butuh bantuan menemukan sebuah buku。',
      'en-US': 'I need help finding a book.',
    }
  },
  {
    id: 'customer_general_10',
    type: 'customer',
    category: 'General Assistance',
    english: 'I lost my library card.',
    translations: {
      'zh-CN': '我丢了我的借书证。',
      'zh-HK': '我唔見咗我嘅圖書證。',
      'ne-NP': 'मेरो पुस्तकालय कार्ड हराएको छ।',
      'el-GR': 'Έχασα την κάρτα βιβλιοθήκης μου。',
      'ar-SA': 'لقد فقدت بطاقة مكتبتي。',
      'mk-MK': 'Ја изгубив мојата библиотечна картичка。',
      'es-ES': 'He perdido mi tarjeta de la biblioteca。',
      'it-IT': 'Ho perso la mia tessera della biblioteca。',
      'id-ID': 'Saya kehilangan kartu perpustakaan saya。',
      'en-US': 'I lost my library card.',
    }
  },
  {
    id: 'customer_general_11',
    type: 'customer',
    category: 'General Assistance',
    english: 'I forgot my PIN.',
    translations: {
      'zh-CN': '我忘记了我的密码。',
      'zh-HK': '我唔記得我嘅密碼。',
      'ne-NP': 'म मेरो पिन बिर्सें।',
      'el-GR': 'Ξέχασα το PIN μου。',
      'ar-SA': 'نسيت رقمي السري。',
      'mk-MK': 'Го заборавив мојот PIN。',
      'es-ES': 'Olvidé mi PIN。',
      'it-IT': 'Ho dimenticato il mio PIN。',
      'id-ID': 'Saya lupa PIN saya。',
      'en-US': 'I forgot my PIN.',
    }
  },
  {
    id: 'customer_general_12',
    type: 'customer',
    category: 'General Assistance',
    english: 'Can I speak to a librarian?',
    translations: {
      'zh-CN': '我可以和图书馆员交谈吗？',
      'zh-HK': '我可以同圖書館員傾談嗎？',
      'ne-NP': 'के म पुस्तकालयकर्मीसँग कुरा गर्न सक्छु?',
      'el-GR': 'Μπορώ να μιλήσω με έναν βιβλιοθηκάριο；',
      'ar-SA': 'هل يمكنني التحدث مع أمين المكتبة؟',
      'mk-MK': 'Можам ли да разговарам со библиотекар？',
      'es-ES': '¿Puedo hablar con un bibliotecario？',
      'it-IT': 'Posso parlare con un bibliotecario？',
      'id-ID': 'Bisakah saya berbicara dengan pustakawan？',
      'en-US': 'Can I speak to a librarian?',
    }
  },
  // Customer Library Layout - additional phrases
  {
    id: 'customer_layout_8',
    type: 'customer',
    category: 'Library Layout',
    english: 'Where is the reference section?',
    translations: {
      'zh-CN': '参考资料区在哪里？',
      'zh-HK': '參考資料區喺邊度？',
      'ne-NP': 'सन्दर्भ खण्ड कहाँ छ?',
      'el-GR': 'Πού είναι το τμήμα αναφοράς；',
      'ar-SA': 'أين قسم المراجع؟',
      'mk-MK': 'Каде е референтниот дел？',
      'es-ES': '¿Dónde está la sección de referencia？',
      'it-IT': 'Dov\'è la sezione di consultazione？',
      'id-ID': 'Di mana bagian referensi？',
      'en-US': 'Where is the reference section?',
    }
  },
  {
    id: 'customer_layout_9',
    type: 'customer',
    category: 'Library Layout',
    english: 'Where is the study area?',
    translations: {
      'zh-CN': '自习室在哪里？',
      'zh-HK': '自習室喺邊度？',
      'ne-NP': 'अध्ययन क्षेत्र कहाँ छ?',
      'el-GR': 'Πού είναι η αίθουσα μελέτης；',
      'ar-SA': 'أين منطقة الدراسة؟',
      'mk-MK': 'Каде е просторот за учење？',
      'es-ES': '¿Dónde está el área de estudio？',
      'it-IT': 'Dov\'è la zona studio？',
      'id-ID': 'Di mana area belajar？',
      'en-US': 'Where is the study area?',
    }
  },
  {
    id: 'customer_layout_10',
    type: 'customer',
    category: 'Library Layout',
    english: 'Where is the magazine section?',
    translations: {
      'zh-CN': '杂志区在哪里？',
      'zh-HK': '雜誌區喺邊度？',
      'ne-NP': 'पत्रिका खण्ड कहाँ छ?',
      'el-GR': 'Πού είναι το τμήμα περιοδικών；',
      'ar-SA': 'أين قسم المجلات؟',
      'mk-MK': 'Каде е делот со списанија？',
      'es-ES': '¿Dónde está la sección de revistas？',
      'it-IT': 'Dov\'è la sezione riviste？',
      'id-ID': 'Di mana bagian majalah？',
      'en-US': 'Where is the magazine section?',
    }
  },
  // Customer Digital Services - additional phrases
  {
    id: 'customer_digital_10',
    type: 'customer',
    category: 'Digital Services',
    english: 'I would like to book a computer session.',
    translations: {
      'zh-CN': '我想预约电脑使用时段。',
      'zh-HK': '我想預約電腦使用時段。',
      'ne-NP': 'म कम्प्युटर सत्र बुक गर्न चाहन्छु।',
      'el-GR': 'Θα ήθελα να κλείσω μια συνεδρία στον υπολογιστή。',
      'ar-SA': 'أود حجز جلسة على الحاسوب。',
      'mk-MK': 'Би сакал да резервирам сесија на компјутер。',
      'es-ES': 'Me gustaría reservar una sesión de ordenador。',
      'it-IT': 'Vorrei prenotare una sessione al computer。',
      'id-ID': 'Saya ingin memesan sesi komputer。',
      'en-US': 'I would like to book a computer session.',
    }
  },
  {
    id: 'customer_digital_11',
    type: 'customer',
    category: 'Digital Services',
    english: 'Can I scan a document?',
    translations: {
      'zh-CN': '我可以扫描文件吗？',
      'zh-HK': '我可以掃描文件嗎？',
      'ne-NP': 'के म कागजात स्क्यान गर्न सक्छु?',
      'el-GR': 'Μπορώ να σαρώσω ένα έγγραφο；',
      'ar-SA': 'هل يمكنني مسح مستند ضوئيًا؟',
      'mk-MK': 'Можам ли да скенирам документ？',
      'es-ES': '¿Puedo escanear un documento？',
      'it-IT': 'Posso scansionare un documento？',
      'id-ID': 'Bisakah saya memindai dokumen？',
      'en-US': 'Can I scan a document?',
    }
  },
  // Customer Language & Community Resources - additional phrases
  {
    id: 'customer_language_5',
    type: 'customer',
    category: 'Language & Community Resources',
    english: 'Do you have books in other languages?',
    translations: {
      'zh-CN': '你们有其他语言的书籍吗？',
      'zh-HK': '你有冇其他語言嘅書？',
      'ne-NP': 'तपाईंसँग अन्य भाषाका किताबहरू छन्?',
      'el-GR': 'Έχετε βιβλία σε άλλες γλώσσες；',
      'ar-SA': 'هل لديكم كتب بلغات أخرى؟',
      'mk-MK': 'Дали имате книги на други јазици？',
      'es-ES': '¿Tienen libros en otros idiomas？',
      'it-IT': 'Avete libri in altre lingue？',
      'id-ID': 'Apakah Anda memiliki buku dalam bahasa lain？',
      'en-US': 'Do you have books in other languages?',
    }
  },
  {
    id: 'customer_language_6',
    type: 'customer',
    category: 'Language & Community Resources',
    english: 'Are there any community programs or events at the library?',
    translations: {
      'zh-CN': '图书馆有社区活动或项目吗？',
      'zh-HK': '圖書館有冇社區活動或節目？',
      'ne-NP': 'पुस्तकालयमा कुनै सामुदायिक कार्यक्रम वा गतिविधिहरू छन्?',
      'el-GR': 'Υπάρχουν κοινοτικά προγράμματα ή εκδηλώσεις στη βιβλιοθήκη；',
      'ar-SA': 'هل توجد برامج أو فعاليات مجتمعية في المكتبة؟',
      'mk-MK': 'Дали има општествени програми или настани во библиотеката？',
      'es-ES': '¿Hay programas o eventos comunitarios en la biblioteca？',
      'it-IT': 'Ci sono programmi o eventi comunitari in biblioteca？',
      'id-ID': 'Apakah ada program atau acara komunitas di perpustakaan？',
      'en-US': 'Are there any community programs or events at the library?',
    }
  },
  {
    id: 'customer_language_7',
    type: 'customer',
    category: 'Language & Community Resources',
    english: 'Do you have newspapers in other languages?',
    translations: {
      'zh-CN': '你们有其他语言的报纸吗？',
      'zh-HK': '你有冇其他語言嘅報紙？',
      'ne-NP': 'तपाईंसँग अन्य भाषाका समाचारपत्रहरू छन्?',
      'el-GR': 'Έχετε εφημερίδες σε άλλες γλώσσες；',
      'ar-SA': 'هل لديكم صحف بلغات أخرى؟',
      'mk-MK': 'Дали имате весници на други јазици？',
      'es-ES': '¿Tienen periódicos en otros idiomas？',
      'it-IT': 'Avete giornali in altre lingue？',
      'id-ID': 'Apakah Anda memiliki koran dalam bahasa lain？',
      'en-US': 'Do you have newspapers in other languages?',
    }
  },
];