// Initial phrases for seeding the database
export const initialPhrases = [
  // Staff Section Phrases
  { 
    id: 'staff_general_1',
    type: 'staff', 
    category: 'General Enquiries', 
    english: 'Please follow me.',
    translations: {
      'zh-CN': '请跟我来。', 
      'zh-HK': '请跟我来。', 
      'ne-NP': 'कृपया मलाई पछ्याउनुहोस्。',
      'el-GR': 'Παρακαλώ ακολουθήστε με。', 
      'ar-SA': 'الرجاء اتبعني。', 
      'mk-MK': 'Ве мо lám следете me。',
      'es-ES': 'Por favor, sígame。', 
      'it-IT': 'Per favor, mi segua。',
      'id-ID': 'Tolong ikiti saya。', 
      'en-US': 'Please follow me.',
    }
  },
  { 
    id: 'staff_general_2',
    type: 'staff', 
    category: 'General Enquiries', 
    english: 'Do you prefer to speak Mandarin or Cantonese?',
    translations: {
      'zh-CN': '您更喜欢说普通话还是粤语？',
      'zh-HK': '你鍾意講普通話定廣東話？',
      'ne-NP': 'तपाईं मन्डारिन वा क्यान्टोनिज बोल्न रुचाउनुहुन्छ?',
      'el-GR': 'Προτιμάτε να μιλάτε Μανδαarinika ή Καντονέζικα？',
      'ar-SA': 'هل تفضل التحدث بالماندرين أو الكانتونية؟',
      'mk-MK': 'Дали претpočitate να зборувате μαndaринiski or кантонски？',
      'es-ES': '¿Prefiere hablar mandarín o cantonés？', 
      'it-IT': 'Preferisce parlare mandarino or cantonese？',
      'id-ID': 'Apakah Anda more like to speak Mandarin or Kanton？',
      'en-US': 'Do you prefer to speak Mandarin or Cantonese?',
    }
  },
  { 
    id: 'staff_general_3',
    type: 'staff', 
    category: 'General Enquiries', 
    english: 'I speak Mandarin.',
    translations: {
      'zh-CN': '我会说普通话。',
      'zh-HK': '我識講普通話。',
      'ne-NP': 'म मन्डारिन बोल्छु。',
      'el-GR': 'Μιλάω Μανδαρινικά。', 
      'ar-SA': 'أنا أتحدث الماندايرين。', 
      'mk-MK': 'Зборуам μαndaринiski。',
      'es-ES': 'Hablo mandarín。', 
      'it-IT': 'Parlo mandarino。',
      'id-ID': 'Saya berbicara Mandarin。', 
      'en-US': 'I speak Mandarin.',
    }
  },
  { 
    id: 'staff_general_4',
    type: 'staff', 
    category: 'General Enquiries', 
    english: 'I speak Cantonese.',
    translations: {
      'zh-CN': '我会说粤语。',
      'zh-HK': '我識講廣東話。',
      'ne-NP': 'म क्यान्टोनिज बोल्छु。',
      'el-GR': 'Μιλάω Καντονέζικα。', 
      'ar-SA': 'أنا أتحدث الكانتونية。', 
      'mk-MK': 'Зoruam кантонски。',
      'es-ES': 'Hablo cantonés。', 
      'it-IT': 'Parlo cantonese。',
      'id-ID': 'Saya berbicara Kanton。', 
      'en-US': 'I speak Cantonese.',
    }
  },
  { 
    id: 'staff_general_5',
    type: 'staff', 
    category: 'General Enquiries', 
    english: 'Please wait one moment',
    translations: {
      'zh-CN': '请稍等片刻。', 
      'zh-HK': '请你稍等一陣。', 
      'ne-NP': 'कृपया एक क्षण पर्खनुहोस्।',
      'el-GR': 'Παρακαλώ περιμένετε μια στιγμή。', 
      'ar-SA': 'الرجاء الانت 기다리다。', 
      'mk-MK': 'Ве моlam počekajte moment。',
      'es-ES': 'Por favor, espere un momento。', 
      'it-IT': 'Per favor, aspetti un momento。',
      'id-ID': 'Mohon tunggu sebentar。', 
      'en-US': 'Please wait one moment',
    }
  },
  { 
    id: 'staff_general_6',
    type: 'staff', 
    category: 'General Enquiries', 
    english: 'I understand.',
    translations: {
      'zh-CN': '我明白了。', 
      'zh-HK': '我明白喇。', 
      'ne-NP': 'मैले बुझें。',
      'el-GR': 'Καταλαβαίνω。', 
      'ar-SA': 'أنا أفهم。', 
      'mk-MK': 'Разбирам。',
      'es-ES': 'Entiendo。', 
      'it-IT': 'Capisco。',
      'id-ID': 'Saya mengerti。', 
      'en-US': 'I understand.',
    }
  },
  { 
    id: 'staff_general_7',
    type: 'staff', 
    category: 'General Enquiries', 
    english: 'Thank you.',
    translations: {
      'zh-CN': '谢谢您。', 
      'zh-HK': '多謝你。', 
      'ne-NP': 'धन्यवाद।',
      'el-GR': 'Ευχαριστώ。', 
      'ar-SA': 'شكرا لك。', 
      'mk-MK': 'Ви благодаруваме。',
      'es-ES': 'Salamat po。', 
      'it-IT': 'Grazie。',
      'id-ID': 'Terima kindness。', 
      'en-US': 'Thank you.',
    }
  },
  { 
    id: 'staff_general_8',
    type: 'staff', 
    category: 'General Enquiries', 
    english: 'You are welcome.',
    translations: {
      'zh-CN': '不客气。', 
      'zh-HK': '唔使客氣。', 
      'ne-NP': 'तपाईंलाई स्वागत छ।',
      'el-GR': 'Παρακαλώ。', 
      'ar-SA': 'على الرحب والسعة。', 
      'mk-MK': 'Неμα na што。',
      'es-ES': 'De nada。', 
      'it-IT': 'Prego。',
      'id-ID': 'Sama-sama。', 
      'en-US': 'You are welcome.',
    }
  },
  { 
    id: 'staff_transactional_1',
    type: 'staff', 
    category: 'Transactional', 
    english: 'Please show me your library card',
    translations: {
      'zh-CN': '请出示您的借书证', 
      'zh-HK': '请出示你的图书证。', 
      'ne-NP': 'कृपया आफ्नो पुस्तकालय कार्ड देखाउनुहोस्।',
      'el-GR': 'Παρακαλώ δείξτε μου την κάρτα βιβλιοθήκης σας。', 
      'ar-SA': 'الرجاء إظهار بطاقة المكتبة الخاصة بك。', 
      'mk-MK': 'Ве мо lám pokažete mi ja vašata bibliotečna kartička。',
      'es-ES': 'Por favor, muéstreme su tarjeta de la biblioteca。', 
      'it-IT': 'Per favor, mi mostri la sua tessera della biblioteca。',
      'id-ID': 'Tolong tunjukkan kartu perpustakaan Anda。', 
      'en-US': 'Please show me your library card',
    }
  },
  { 
    id: 'staff_transactional_2',
    type: 'staff', 
    category: 'Transactional', 
    english: 'Would you like to create a library card? It is free of charge.',
    translations: {
      'zh-CN': '您想办一张借书证吗？这是免费的。', 
      'zh-HK': '你想申请张图书证吗？系免费嘅。', 
      'ne-NP': 'के तपाईं पुस्तकालय कार्ड बनाउन चाहनुहुन्छ? यो निःशुल्क छ।',
      'el-GR': 'Θα θέlaτε να βγάλετε κάρτα βιβλιοθήκης; Είναι δω ücretsiz。', 
      'ar-SA': 'هل ترغب في إنشاء بطاقة مكتبة؟إنها مجانية。', 
      'mk-MK': 'Дали сакате да napravite bibliotečna kartička? Besplatno e。',
      'es-ES': '¿Le gustaría crear una tarjeta de la biblioteca? Es gratis。', 
      'it-IT': 'Le piacerebbe creare una tessera della biblioteca? È gratuita。',
      'id-ID': 'Apakah Anda ingin membuat kartu perpustakaan? This is free of charge。', 
      'en-US': 'Would you like to create a library card? It is free of charge.',
    }
  },
  { 
    id: 'staff_transactional_3',
    type: 'staff', 
    category: 'Transactional', 
    english: 'Would you like to borrow these items?',
    translations: {
      'zh-CN': '您想借阅这些物品吗？', 
      'zh-HK': '你想借呢啲嘢嗎？', 
      'ne-NP': 'के तपाईं यी सामानहरू उधारो लिन चाहनुहुन्छ?',
      'el-GR': 'Θα θέlaτε να δανειστείτε αυτά τα αντικείμενα？', 
      'ar-SA': 'هل ترغب في استعارة هذه المواد؟', 
      'mk-MK': 'Дали сакате da gi pozajmite ovie predmeti？',
      'es-ES': '¿Le gustaría pedir prestados estos artículos？', 
      'it-IT': 'Le piacerebbe prendere in prestito these items？',
      'id-ID': 'Apakah Anda ingin meminjam barang-abag this？', 
      'en-US': 'Would you like to borrow these items?',
    }
  },
  { 
    id: 'staff_transactional_4',
    type: 'staff', 
    category: 'Transactional', 
    english: 'Would you like to return these items?',
    translations: {
      'zh-CN': '您想归还这些物品吗？', 
      'zh-HK': '你想还呢啲嘢嗎？', 
      'ne-NP': 'के तपाईं यी सामानहरू फिर्ता गर्न चाहनुहुन्छ?',
      'el-GR': 'Θα θέlaτε να επιστρέψετε αυτά τα αντικείμενα？', 
      'ar-SA': 'هل ترغب في إرجاع هذه المواد؟', 
      'mk-MK': 'Дали сакате da gi vratite ovie predmeti？',
      'es-ES': '¿Le gustaría devolver estos artículos？', 
      'it-IT': 'Le piacerebbe restituire these items？',
      'id-ID': 'Apakah Anda ingin mengembalikan barang-barang this？', 
      'en-US': 'Would you like to return these items?',
    }
  },
  // Add more phrases as needed...
]; 